language: none

#runtime:
 # - nodePool: custom__x86_64__Ubuntu_16_04
 # - nodePool: dynamic__x86_64__Ubuntu_16_04__c4_large
 # - nodePool: dynamic__x86_64__Ubuntu_14_04__c4_xlarge
 # - nodePool: dynamic__x86_64__CentOS_7__c4_large
 # - nodePool: default-restricted
  
build:
    
  ci: 
    - echo "Hello!"

resources:
  - name: conf-ymlrepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: Varsha-Arun/conf-yml
      branch: pipelinesimplerunsh-pr1

jobs:
  - name: simplerunsh
    type: runSh
    steps:
      - IN: conf-ymlrepo
      - TASK:
        - script: ls
        - script: ./IN/conf-ymlrepo/gitRepo/script.sh
    always:
      - script: echo "This works on_always"
